### ISSUE TITLE
Project yiisoft/demo failed to add yiisoft/yii-gii

### ISSUE THREAD

**Issue by RicardoSette** [yiisoft/yii-gii#44] opened 2021-09-24 13:32 UTC
### What steps will reproduce the problem?

composer create-project yiisoft/demo --prefer-dist --stability=dev 
composer update
composer require --prefer-dist yiisoft/yii-gii

### What is the expected result?
run from command line yii with gii

### What do you get instead?
```shell
% php yii

Fatal error: Uncaught ErrorException: Duplicate key "Yiisoft\Rbac\StorageInterface" in configs:
 - config/packages/yiisoft/yii-gii/$common in /usr/home/dev/yii3/test/vendor/yiisoft/config/src/Config.php:379
Stack trace:
#0 /usr/home/dev/yii3/test/vendor/yiisoft/config/src/Config.php(250): Yiisoft\Config\Config->throwException('Duplicate key "...')
#1 /usr/home/dev/yii3/test/vendor/yiisoft/config/src/Config.php(114): Yiisoft\Config\Config->merge(Array, '', Array, Array)
#2 /usr/home/dev/yii3/test/vendor/yiisoft/config/src/Config.php(82): Yiisoft\Config\Config->buildGroup('console', '/')
#3 /usr/home/dev/yii3/test/src/Runner/ConsoleApplicationRunner.php(50): Yiisoft\Config\Config->get('console')
#4 /usr/home/dev/yii3/test/yii(25): App\Runner\ConsoleApplicationRunner->run()
#5 {main}
  thrown in /usr/home/dev/yii3/test/vendor/yiisoft/config/src/Config.php on line 379
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | PHP 8.0.10
| Operating system | FreeBSD domainName 12.2-RELEASE FreeBSD 12.2-RELEASE r366954 GENERIC  amd64

To solve the problem I just commented one line:
```diff
% diff -urNa -U10 ../test2/config/packages/merge_plan.php config/packages/merge_plan.php 
--- ../test2/config/packages/merge_plan.php	
+++ config/packages/merge_plan.php	
@@ -86,21 +86,21 @@
         ],
         'console' => [
             '/' => [
                 '$common',
                 'config/console/*.php',
             ],
             'yiisoft/yii-cycle' => [
                 'console.php',
             ],
             'yiisoft/yii-gii' => [
-                '$common',
+//                '$common',
                 'console.php',
             ],
             'yiisoft/translator-extractor' => [
                 'console.php',
             ],
             'yiisoft/yii-console' => [
                 'console.php',
             ],
             'yiisoft/yii-event' => [
                 'console.php',
```

I believe it is due to the duplication in composer.json:
```shell
% grep -B5 -A5 '\$common' vendor/yiisoft/yii-gii/composer.json
            "source-directory": "config"
        },
        "config-plugin": {
            "params": "params.php",
            "console": [
                "$common",
                "console.php"
            ],
            "common": "common.php"
        }
    },
```

Any other suggestions for fixing the problem? or would this fix be recommended?

**Comment by samdark** [comment] 2021-09-27 21:20
Gii is under heavy development right now so it's no point installing it now.

**Comment by hunwalk** [comment] 2021-11-22 14:33
If you copy the configuration from the config dir into your configuration you will get this: 
![obrázok](https://user-images.githubusercontent.com/32835435/142879406-ecde9609-7c27-4da7-9264-245e3976728f.png)

Is there something I'm missing?

**Comment by rustamwin** [comment] 2021-11-22 14:54
Gii is missing changes from other packages. As @samdark told this package is under heavy development. We will fix and adapt to other packages soon.

**Comment by xepozz** [comment] 2022-09-21 13:01
Fixed in: https://github.com/yiisoft/yii-gii/pull/51
PR in demo waiting for the previous one will be merged: https://github.com/yiisoft/demo/pull/504

**Comment by ahmadasjad** [comment] 2024-09-10 09:57
The problem is not coming with the latest master branch, so closing this is okay.

**Closed** 2024-09-10 17:14 UTC
Labels: type:bug, status:ready for adoption
